### PR TITLE
Build: Use a 6.0.200 SDK and macos workload P13

### PR DESCRIPTION
**Pull request by sandyarmstrong**

### CODE REVIEW

**Comment by sandyarmstrong** [comment]
@BretJohnson @mcumming you ok with merging this? We're trying to get the Xamarin extension submodules merged now.

**Comment by sandyarmstrong** [comment]
@emaf could use your review too, I don't have any authority in this repo. 😄

**Review by emaf — APPROVED** [review]

**Comment by emaf** [comment]
It looks good to me, @BretJohnson are you folks okay with merging this into main?

**Comment by BretJohnson** [comment]
Yes. Merged.

**Comment by BretJohnson** [comment]
@emaf - Feel free to bump it in vsmac-xamarin-extensions.

**Pull request merged**
